### ISSUE TITLE
Markierung von beispielsweise häufigen wissenschaftlichen Fehlern

### ISSUE THREAD

**Issue by Dimmerli** [Darkgaja/Docdown#1]
Es wäre eine Funktion hilfreich mit dem man durch das template definierte Wörter und Ausdrücke mit regular expressions angeben kann.
Diese werden dann vom Editor hervor gehoben und bieten eventuell sogar Alternativen an. Es sollte immer eine Beschreibung des Fehlers angezeigt werden. Bei falschen Positiven sollte man die Markierung ignorieren können.

Klassische Fehler wären: 
ich -> "Wissenschaftliche Arbeiten werden aus 3. Person geschrieben. Schreiben Sie den Satz allgemein gültig auf. Wenn Sie Meinung dadurch mitteilen, überprüfen Sie, ob das in dieser Arbeit erlaubt ist."

Ein allgemeiner Fehler wären Wortwiederholungen. Dabei kann automatisch ein Thesaurusvorschlag angezeigt werden.

Wörter in Großbuchstaben könnten markiert werden, da sie potentiell Abkürzungen sind und ins Abkürzungsverzeichnis gehören.

**Comment by Darkgaja** [comment]
Klassische Fehler, also Wörter wie "ich", "man", "eigentlich", etc. zu markieren wurde in https://github.com/Darkgaja/Docdown/commit/167f59b4226be940f6e2234cc90a8137e45c1562 hinzugefügt.

Wortwiderholungen über mehrere Sätze hinweg zu erkennen, wie sie in wissenschaftlichen Arbeiten häufig auftreten, ist automatisiert sehr schwierig. Daher wird das nicht umgesetzt.

Automatische Erkennung von Abkürzungen folgt noch in einem zukünftigen Commit.

**Comment by Darkgaja** [comment]
Abkürzungen, die nicht durch latex als solche gekennzeichnet werden, sind durch 35ec712 nun blau als Informationen markiert.
