### ISSUE TITLE
Sources: Internal links in the PDF

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#14]
It would be great if quoted sources like `"Blabla BlaBla [3]"` could get a link to the corresponding source in the source directory. 

So one would only have to press on the quoted source in the text and could find this directly in the source directory. 

To be honest, I'm not so sure if this is feasible at all... ;)

**Comment by Darkgaja** [comment]
Great question!

I've looked into it, and as the backend is using [pandoc-citeproc](https://github.com/jgm/pandoc-citeproc), you can already generate a link to each bibliography entry. Simply enter `link-citations: true` into the meta data block at the start of your markdown file.

In the next server update I will probably set `link-citations: true` by default. I don't see how this change could affect anyone detrimentally.

Also, this probably should go into the usage section of the readme file.
