### ISSUE TITLE
Mark the previously written text in the search bar

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#16]
When I press `Ctrl + F` twice in a row to search something in my markdown file, I always write after the previously typed search term. 

It would be great if when activating the search bar the previously written one would be marked so that the user can decide whether he wants to delete it quickly or keep it.

![grafik](https://user-images.githubusercontent.com/52296146/70068064-9f2b3f00-15ef-11ea-82f5-a7482c5fad1c.png)

**Comment by Darkgaja** [comment]
Added with 3ecf9fa.
