### ISSUE TITLE
Searchbar broken

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#19]
After [3ecf9fa](https://github.com/Darkgaja/Docdown/commit/3ecf9fabbcf52052061737b9a9930703529247f9) the searchbar is broken. This commit was made to include issue #16. It is broken the following: 

- When I type `Ctrl + F` the searchbar opens but the cursor is not placed in the searchbar. Because of this I write into my normal text although the bar is open and just activated. 

- But if I click into the search bar with the mouse and press `Ctrl + F` again, it automatically marks the previous search text and deletes it at the next keystroke.

**Comment by Darkgaja** [comment]
Fix released in Version 0.3.2.0
