### ISSUE TITLE
DocDown crashes with duplicates in bib file

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#21]
I accidentally added a duplicate source to my `bib` file. Both sources had the same "IDs" and were referenced the same way in the markdown text. 

At that moment the program crashed without a message and could not be opened again because the workspace of the project was selected by default. After deleting one of the two sources, DocDown ran stable as usual.

**Comment by Darkgaja** [comment]
Fix released in Version 0.3.2.0
