### ISSUE TITLE
Showing ping to server when compiling online

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#25]
It would be very usefull to see the current `ping` to the compiling Sloppy-Server when compiling online. For example beside the `Kompilierung...` text. 

This feature would be a nice addon when compiling with slow internet.

![grafik](https://user-images.githubusercontent.com/52296146/70847222-356a2b00-1e62-11ea-83f0-d7e99bab5236.png)

**Comment by Darkgaja** [comment]
Do you mean slow internet as in a low bandwidth or as in a high latency? I could easily include a roundtrip time for example as a tooltip in the settings window. But I don't really see the necessity in a low bandwidth indicator.

**Comment by FForthmann** [comment]
I meant high latency to the server. This could also be due to the internet connection at my place. 

It is also really only an extra, which occurred to me so besides. :) 

I personally would find an indicator with the latency to the server very practical to see if long compilation times come from the large amount of data I send, or if I simply currently have bad Internet.

**Comment by Darkgaja** [comment]
Added in 96f5cfe. Released in version 0.3.3.0

The latency is now shown when hovering over the connection button in the settings window. Hitting the button causes the latency to refresh. 

Viewing the latency after startup may cause it to seem way to high. Simply refreshing it will show you the correct value.
