### ISSUE TITLE
Do not compile flag for files and folders

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#26]
At the moment DocDown sends the whole folder in which the `Strategy.md` is to the server to compile. This can cause to unexplainable failures during compiling when the folder also includes other large files e.g. skripts. 

It would be nice if one could mark files and folders which do not have to be send to the server. For example in an extra file or in the meta-block.

Containing also not compilable data in the main folder is espacially usefull when you want to verion your work via Git e.g.

**Comment by Darkgaja** [comment]
Added in d4fe320. Released with 0.3.3.0.

Files and folders you want to exclude from compilation can be selected via a button in the context menu of the workspace explorer. They can be included the same way again. Excluded items are slightly transparent.
