### ISSUE TITLE
Crash after renaming files

### ISSUE THREAD

**Issue by Dimmerli** [Darkgaja/Docdown#29]
How to reproduce:

1. Create two files.
2. Call them "01" and "02" and open them in the editor
3. Rename "01" to "03" and thereby change the order of the files
4. Switch between the editors

Result: Displayed editors don't update and the program crashes.

**Comment by Darkgaja** [comment]
After looking at [this](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c27733eb-61ad-4f05-b7f8-502e70ee35e9/an-item-with-the-same-key-has-already-been-added?forum=wpf&prof=required) post, it looks like the renaming results in the object returning a different hash code. The Tab Control uses the hash code to keep track of the item and a changing hash code results in an internal error some dictionary.

We will fix this by keeping track of the original hash code.
