### ISSUE TITLE
Translation missing: Document Language 

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#5]
When changing languages from english to german, the tab `Document Language` with its details is not translated.

![translation](https://user-images.githubusercontent.com/52296146/69247326-86139e80-0baa-11ea-9cbe-ab6fc1a01830.PNG)

**Comment by Darkgaja** [comment]
I'm currently working on automatically identifying the document language (which is only used for validation currently). The menu item in question will propably be removed by the next update.
