### ISSUE TITLE
Compile-server not available because of automatically configured proxy

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#7]
In DocDown, the connection to the server fails without an error message. 

Solution: This is due to a proxy configured by Windows. 
To reset the proxy, use the following command: `netsh winhttp reset proxy` in the poweshell. 

It would be useful to have the server run DocDown right from the start or to initialize a corresponding error message. If necessary you have to pay attention to local admin rights, because the command can only be executed as admin.

**Comment by Darkgaja** [comment]
Docdown now resets WinHTTP proxies on application startup as of 507e945.

This is done programmatically instead via the powershell command. Doing this will usually not require admin access, unless the per-machine proxy policy is set.
