### ISSUE TITLE
Wish: Shortcut for compiling the project

### ISSUE THREAD

**Issue by FForthmann** [Darkgaja/Docdown#9]
It would be very useful to have or be able to specify a shortcut to compile the project / create the PDF in addition to the classic `Ctrl + S` for saving. This could then be displayed at the top when hovering over the icon.

![grafik](https://user-images.githubusercontent.com/52296146/69548574-dff3da00-0f97-11ea-9765-44dc63a8b46b.png)

**Comment by Darkgaja** [comment]
Pressing `F5` is the shortcut for compilation currently.

In a recent update I've broken the tooltip for the start button, usually the respective shortcut would show up there.
